### ISSUE TITLE
MainActivity docs

### ISSUE THREAD

**Issue by DarrylD** [rhaker/react-native-sms-android#3]
Made a fresh install of RN from source and looks like so:

```
package com.awesomeproject;

import com.facebook.react.ReactActivity;


public class MainActivity extends ReactActivity {
    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "AwesomeProject";
    }
}
```

Not sure how to add the proper packages.

**Comment by DarrylD** [comment]
Tried this and was able to build:

```
package com.awesomeproject;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactPackage;

import java.util.Arrays;
import java.util.List;


import com.rhaker.reactnativesmsandroid.RNSmsAndroidPackage;

public class MainActivity extends ReactActivity {

    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new RNSmsAndroidPackage()
      );
    }

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "AwesomeProject";
    }
}
```

But in js:

```
var SmsAndroid = require('react-native-sms-android');

console.log(SmsAndroid) // <-- undefined
```

Any idea why?

**Comment by rhaker** [comment]
Hey @DarrylD. Thanks for trying out the package. RN has made a major change to the way android was compiled on version 0.29. I built the original module and docs for an earlier version. And I haven't had to use this module on a project with v0.29+. The code for v0.29 was a recent pull request by @sharafat - so perhaps they can respond?

My only comments would be to make sure of the following:
1) you are running on a device (sometimes the emulator has problems with sms)
2) you have included the proper config in android/setting.gradle and in android/app/build.gradle
3) make sure you have included the permissions in AndroidManfiest.xml
4) try the full example code in js using the indirect method and see if you get the chooser popup. By full code, I mean:

SmsAndroid.sms(
  '123456789', // phone number to send sms to
  'This is the sms text', // sms body
  'sendDirect', // sendDirect or sendIndirect
  (err, message) => {
    if (err){
      console.log("error");
    } else {
      console.log(message); // callback message
    }
  }
);

**Comment by sharafat** [comment]
@rhaker, I've created a [pull request](https://github.com/rhaker/react-native-sms-android/pull/4) which updates the doc with instructions on installation on RN 0.29+.

@DarrylD: Sorry that when creating the pull request for upgrading the library, I didn't have time to update the docs. You can now view the changes required to properly install the module on RN 0.29+ once the pull request gets merged, or right now at that pull request. Basically you need to declare the module inside the `MainApplication` class instead of `MainActivity`. 

Afterwards, `var SmsAndroid = require('react-native-sms-android');` should work fine; but in the awkward case that it doesn't, try `import SmsAndroid from "react-native-sms-android";`.

**Comment by DarrylD** [comment]
@rhaker @sharafat Thanks for the quick response!

It was the fact that the docs were old. I just started using RN at version 30 so wasn't aware of the old way but, working fine!

Thanks again!
