### ISSUE TITLE
If you will copy my code please dont forget to remove my phone # prefix from the example

### ISSUE THREAD

**Issue by msmakhlouf** [rhaker/react-native-sms-android#8]
https://github.com/msmakhlouf/react-native-android-sms 
@rhaker

**Comment by rhaker** [comment]
Hello! It seems that @DarrylD was the contributor that pulled your code into the repo. The issue was described here: https://github.com/rhaker/react-native-sms-android/issues/5. I don't think your code was in the repo prior to that merge. @sharafat was the contributor who modified the repo before that. 

Are you not okay with the list feature code being in this module?

All the best.
